// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAfwHtOKx6VKIE30ov2Dy36J-R0nZ4qWY',
    appId: '1:280979689883:web:c6ea0773998cdfeb54913e',
    messagingSenderId: '280979689883',
    projectId: 'pc-bma-project',
    authDomain: 'pc-bma-project.firebaseapp.com',
    storageBucket: 'pc-bma-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPiE-8Bj_boJu5Vlyrg87tob2m4m1Y48',
    appId: '1:280979689883:android:b03ef4a56c72557e54913e',
    messagingSenderId: '280979689883',
    projectId: 'pc-bma-project',
    storageBucket: 'pc-bma-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCo6E82fH6fvfHR9WzhvbRtRRgsgHm1vg',
    appId: '1:280979689883:ios:5982dd50059c22fe54913e',
    messagingSenderId: '280979689883',
    projectId: 'pc-bma-project',
    storageBucket: 'pc-bma-project.firebasestorage.app',
    iosBundleId: 'com.example.pcBma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCo6E82fH6fvfHR9WzhvbRtRRgsgHm1vg',
    appId: '1:280979689883:ios:5982dd50059c22fe54913e',
    messagingSenderId: '280979689883',
    projectId: 'pc-bma-project',
    storageBucket: 'pc-bma-project.firebasestorage.app',
    iosBundleId: 'com.example.pcBma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAfwHtOKx6VKIE30ov2Dy36J-R0nZ4qWY',
    appId: '1:280979689883:web:ced5a9707c04490054913e',
    messagingSenderId: '280979689883',
    projectId: 'pc-bma-project',
    authDomain: 'pc-bma-project.firebaseapp.com',
    storageBucket: 'pc-bma-project.firebasestorage.app',
  );
}
